
[[redirects]]
  from = "/fundraisingbox/*"
  to = "https://secure.fundraisingbox.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"
