name: Update Donation Data

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-donation-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Fetch donation data and update file
        run: |
          RESPONSE=$(curl -s "https://secure.fundraisingbox.com/app/projectItemJson?hash=Z%2Ff4DQAHzKQ4J%2ByEUM7POQ%3D%3D")
          if [ $? -ne 0 ]; then
            echo "Error: Failed to fetch donation data"
            exit 1
          fi
          cat > ./src/data/donationData.ts << EOL
          export interface DonationData {
            item_id: number;
            item_name: string;
            item_amount: number;
            form_url: string;
            project_donations_goal: number;
            project_donations_amount: number;
            project_donations_count: number;
          }
          export const donationData: DonationData = $RESPONSE;
          EOL
          echo "Donation data updated successfully"

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add ./src/data/donationData.ts
          git diff --staged --quiet || (git commit -m "Update donation data [skip ci]" && \
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git && \
          git push)
